accounting/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
admin.autodiscover()


urlpatterns = [
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^account/", include("account.urls")),
    url(r'^businesses/', include('apps.businesses.urls', namespace="businesses")),
    url(r'^customers/', include('apps.customers.urls', namespace="customers")),
    url(r'^invoices/', include('apps.invoices.urls', namespace="invoices")),
    url(r'^quotes/', include('apps.quotes.urls', namespace="quotes")),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('businesses:list')), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/api/customers/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from rest_framework import routers
from django.conf.urls import url, include
from .views import CustomerViewSet

router = routers.DefaultRouter()
router.register(r'customers', CustomerViewSet)

urlpatterns = [
    url(r'^', include(router.urls))
]

apps/customers/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from . import views
from apps.contribs.regex.url import UUID4_REGEX_PARAM

urlpatterns = [
    url(r'^{}$'.format(UUID4_REGEX_PARAM), views.UpdateCustomerView.as_view(), name="update"),
    url(r'^create$', views.CreateCustomerView.as_view(), name="create"),
    url(r'^(?P<page>\d+)$', views.ListCustomerView.as_view(), name="list"),
    url(r'^$', views.ListCustomerView.as_view(), name="list"),
]

apps/customers/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from apps.contribs.models import BaseModel


class Customer(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=255)
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    post_code = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)

    def get_absolute_url(self):
        return reverse('customers:update', args=[self.uuid])

    @property
    def last_invoice(self):
        return self.invoices.order_by('-id').first()

apps/customers/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from .models import Customer
import floppyforms.__future__ as forms


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ['uuid', 'user']

apps/api/customers/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from rest_framework import viewsets
from apps.customers.models import Customer
from apps.api.contribs.views import FilterUserMixin, UUIDMixin, AutoOwnerMixin
from apps.api.contribs.permissions import IsOwnerPermission
from .serializers import CustomerSerializer


class CustomerViewSet(AutoOwnerMixin, UUIDMixin, FilterUserMixin, viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    permissions = [IsOwnerPermission]

apps/customers/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.views.generic import CreateView, UpdateView, ListView
from apps.contribs.views.mixins import NormalSecurityMixin, AutoUserMixin, OwnerQuerySetMixin
from .models import Customer
from .forms import CustomerForm


class CreateCustomerView(NormalSecurityMixin, AutoUserMixin, CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/create.html'


class UpdateCustomerView(NormalSecurityMixin, UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/update.html'
    slug_url_kwarg = 'uuid'
    slug_field = 'uuid'


class ListCustomerView(NormalSecurityMixin, OwnerQuerySetMixin, ListView):
    model = Customer
    template_name = 'customers/list.html'

templates/customers/base.html
{% extends 'base.html' %}

templates/customers/create.html
{% extends 'customers/base.html' %}

{% block page_header %}Create Customer{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
          <form method="POST" class="form-horizontal">
              {% csrf_token %}
              {{ form }}
              <input class="btn btn-primary" type="submit" value="Create"/>
          </form>
      </div>
  </div>
{% endblock %}

templates/customers/list.html
{% extends 'customers/base.html' %}
{% load humanize %}

{% block page_header %}All Customers <a href="{% url 'customers:create' %}" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
              <th>Name</th><th>Last Invoice</th><th>Issued From</th><th>Issued at</th><th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          {% with last_invoice=object.last_invoice %}
          <tr>
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
            </td>
            <td>
              <a href="{{ last_invoice.get_absolute_url }}"><span class="label label-primary">{{ last_invoice.number }}</span></a>
            </td>
            <td>
              {{ last_invoice.business }}
            </td>
            <td>
              {{ last_invoice.created|naturaltime }}
            </td>
            <td>
              <a class="btn btn-primary" href="{% url 'invoices:create' %}?customer={{ object.id }}">+ Invoice</a>
            </td>
          </tr>
          {% endwith %}
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-md-12 pagination-centered text-center">
          {% include 'partials/pagination.html' with urlname='customers:list' %}
      </div>
    </div>
{% endblock %}

templates/customers/update.html
{% extends 'customers/base.html' %}

{% block page_header %}Update Customer: {{ object.name }}{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
          <form method="POST" class="form-horizontal">
              {% csrf_token %}
              {{ form }}
              <input class="btn btn-primary" type="submit" value="Update"/>
          </form>
      </div>
  </div>
{% endblock %}