accounting/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
admin.autodiscover()


urlpatterns = [
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^account/", include("account.urls")),
    url(r'^businesses/', include('apps.businesses.urls', namespace="businesses")),
    url(r'^customers/', include('apps.customers.urls', namespace="customers")),
    url(r'^invoices/', include('apps.invoices.urls', namespace="invoices")),
    url(r'^quotes/', include('apps.quotes.urls', namespace="quotes")),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('businesses:list')), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/api/invoices/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from rest_framework import routers
from django.conf.urls import url, include

from apps.contribs.regex.url import UUID4_REGEX_PARAM
from .views import InvoiceViewSet, SendEmailView, LineItemViewSet

router = routers.DefaultRouter()
router.register('invoices', InvoiceViewSet)
router.register('lineitem', LineItemViewSet)

urlpatterns = [
    url(r'^send-email/{}$'.format(UUID4_REGEX_PARAM), SendEmailView.as_view(), name='send_email'),
    url(r'^', include(router.urls)),
]

apps/invoices/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from . import views
from apps.contribs.regex.url import UUID4_REGEX_PARAM


urlpatterns = [
    url(r'^{}$'.format(UUID4_REGEX_PARAM), views.UpdateInvoiceView.as_view(), name="update"),
    url(r'^{}/pdf$'.format(UUID4_REGEX_PARAM), views.InvoicePDFView.as_view(), name="pdf"),
    url(r'^{}/embed-pdf$'.format(UUID4_REGEX_PARAM), views.InvoicePDFEmbededView.as_view(), name="embed_pdf"),
    url(r'^create$', views.CreateInvoiceView.as_view(), name="create"),
    url(r'^overdue/(?P<page>\d+)$', views.ListOverdueInvoiceView.as_view(), name="overdue"),
    url(r'^overdue$', views.ListOverdueInvoiceView.as_view(), name="overdue"),
    url(r'^(?P<page>\d+)$', views.ListInvoiceView.as_view(), name="list"),
    url(r'^$', views.ListInvoiceView.as_view(), name="list"),
]

apps/invoices/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import unicode_literals

from datetime import timedelta

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.timezone import now
from django.contrib.sites.models import Site
from django.core.mail import EmailMultiAlternatives
from apps.contribs.models import BaseModel
from apps.contribs.security.token import get_user_token
from decimal import Decimal
from .managers import InvoiceQuerySet
import requests


class Invoice(BaseModel):
    number = models.IntegerField(blank=True)
    business = models.ForeignKey('businesses.Business', related_name="invoices")
    customer = models.ForeignKey('customers.Customer', related_name="invoices")
    due_date = models.DateField(blank=True)
    paid_at = models.DateField(null=True, blank=True)
    invalid = models.BooleanField(default=False, blank=True)
    objects = InvoiceQuerySet.as_manager()

    def __unicode__(self):
        return u'{} {} -> {}'.format(self.number, self.business, self.customer)

    def get_absolute_url(self):
        return reverse('invoices:update', args=[self.uuid])

    def get_absolute_pdf_url(self, use_token=False):
        if use_token:
            return '{}/pdf?token={}&user={}'.format(reverse('invoices:update', args=[self.uuid]), get_user_token(self.business.user), self.business.user.id)
        return '{}/pdf'.format(reverse('invoices:update', args=[self.uuid]))

    def send_email(self, body=None, to=None, title=None):
        body = body or ''
        to = to or [self.customer.email]
        title = title or 'You have received an invoice from {}'.format(self.business)
        site = Site.objects.get_current()
        mail = EmailMultiAlternatives(
            subject=title,
            body=body,
            from_email='{} <{}>'.format(self.business, self.business.email),
            to=to
        )

        # attach pdf file
        pdf = requests.get('{}://{}{}'.format(settings.HTTP_SCHEME, site.domain, self.get_absolute_pdf_url(use_token=True)), verify=False, stream=True).raw.read()
        mail.attachments = [('{}.pdf'.format(self.number), pdf, 'application/pdf')]
        mail.attach_alternative(body, "text/html")
        mail.send()

    @property
    def total(self):
        return sum(lineitem.subtotal for lineitem in self.line_items.all())

    @property
    def tax_amount(self):
        return sum(lineitem.tax_amount for lineitem in self.line_items.all())

    @property
    def total_include_tax(self):
        return self.total + self.tax_amount

    @property
    def is_overdue(self):
        return not self.invalid and self.due_date < now().date() and self.paid_at is None

    def save(self, *args, **kwargs):
        if not self.number:
            last_number = Invoice.objects.filter(business=self.business).aggregate(models.Max('number'))['number__max']
            if last_number:
                self.number = last_number + 1
            else:
                self.number = self.business.initial_invoice_number

        if not self.due_date:
            self.due_date = timezone.now() + timedelta(days=30)
        return super(Invoice, self).save(*args, **kwargs)


    class Meta:
        ordering = ['-number']
        unique_together = ['number', 'business']


class LineItem(models.Model):
    invoice = models.ForeignKey('Invoice', related_name='line_items')
    particular = models.CharField(max_length=255)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.DecimalField(max_digits=6, decimal_places=2)
    tax = models.DecimalField(max_digits=5, decimal_places=4, null=True, blank=True)

    @property
    def subtotal(self):
        return (self.unit_price * self.quantity).quantize(Decimal('0.00'))

    @property
    def tax_amount(self):
	tax = self.invoice.business.default_tax
	if self.tax is not None:
		tax = self.tax	
        return (self.subtotal * tax).quantize(Decimal('0.00'))

    @property
    def subtotal_include_tax(self):
        return self.subtotal + self.tax_amount


class Theme(BaseModel):
    default = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=255, default='invoices/pdf/default/')

apps/invoices/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from .models import Invoice, LineItem
from datetime import timedelta
from django.utils import timezone
from django.db import models
from django import forms as django_forms
from apps.businesses.models import Business
from apps.customers.models import Customer
from apps.contribs.forms.widgets import PercentageInput
from apps.contribs.forms.fields import PercentageField
import floppyforms.__future__ as forms


class InvoiceCreateForm(forms.ModelForm):
    class Meta:
        model = Invoice
        exclude = ['uuid', 'user', 'paid_at', 'invalid', 'due_date']

    def __init__(self, request, *args, **kwargs):
        super(InvoiceCreateForm, self).__init__(*args, **kwargs)
        self.fields['business'].queryset = Business.objects.filter(user=request.user)
        self.fields['customer'].queryset = Customer.objects.filter(user=request.user)
        self.fields['number'].widget = forms.widgets.NumberInput(attrs={'placeholder': 'Empty for auto number'})


class InvoiceUpdateForm(InvoiceCreateForm):
    class Meta:
        model = Invoice
        exclude = ['uuid', 'user']


class LineItemForm(django_forms.ModelForm):
    tax = PercentageField(required=False, widget=PercentageInput(attrs={'placeholder':'Empty for default tax', 'step': 'any'}))

    class Meta:
        model = LineItem
        fields = ['particular', 'unit_price', 'quantity', 'tax']

    def __init__(self, *args, **kwargs):
        super(LineItemForm, self).__init__(*args, **kwargs)
        self.fields['particular'].widget = forms.widgets.TextInput(attrs={'size': 40})

apps/api/invoices/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework import serializers
from rest_framework.views import APIView
from rest_framework.response import Response
from apps.invoices.models import Invoice, LineItem
from apps.api.contribs.views import UUIDMixin
from .serializers import InvoiceSerializer, LineItemSerializer
import logging

log = logging.getLogger(__name__)


class IsOwnerPermission(permissions.IsAuthenticated):
    """
    slight variation of the one in api.contribs
    """

    def has_object_permission(self, request, view, obj):
        return self.obj.business.user == self.request.user


class InvoiceViewSet(UUIDMixin, viewsets.ModelViewSet):
    queryset = Invoice.objects.all()
    serializer_class = InvoiceSerializer
    permissions = [IsOwnerPermission]

    def get_queryset(self):
        return self.queryset.filter(business__user=self.request.user)

    def validate_fk(self, serializer):
        """
        checks if fk is owned by the user
        """
        try:
            assert serializer.validated_data['business'].user == self.request.user
        except:
            raise serializers.ValidationError('Incorrect business specified.')

        try:
            assert serializer.validated_data['customer'].user == self.request.user
        except:
            raise serializers.ValidationError('Incorrect customer specified.')

        # if len(serializer.validated_data['line_items']) > 20:
        #    raise serializers.ValidationError('Too many line items.')

    def perform_create(self, serializer):
        self.validate_fk(serializer)
        return super(InvoiceViewSet, self).perform_create(serializer)

    def perform_update(self, serializer):
        self.validate_fk(serializer)
        return super(InvoiceViewSet, self).perform_update(serializer)


class SendEmailView(APIView):

    def post(self, request, uuid, format=None):
        invoice = Invoice.objects.get(uuid=uuid, business__user=request.user)
        invoice.send_email()
        return Response(True)


class LineItemViewSet(UUIDMixin, viewsets.ModelViewSet):
    queryset = LineItem.objects.all()
    serializer_class = LineItemSerializer

apps/invoices/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
import logging
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, ListView, DetailView
from django.template import Context
from django.template.loader import get_template
from django.contrib import messages
from apps.contribs.views.mixins import NormalSecurityMixin, AutoUserMixin, OwnerQuerySetMixin, InjectRequestFormMixin, TokenSecurityMixin
from extra_views import UpdateWithInlinesView, InlineFormSet
from wkhtmltopdf.views import PDFTemplateView
from .models import Invoice, LineItem
from .forms import LineItemForm, InvoiceCreateForm, InvoiceUpdateForm

log = logging.getLogger(__name__)


class ListInvoiceView(NormalSecurityMixin, OwnerQuerySetMixin, ListView):
    model = Invoice
    template_name = 'invoices/list.html'
    user_field_name = 'business__user'

    def get_context_data(self, **kwargs):
        ctx = super(ListInvoiceView, self).get_context_data(**kwargs)
        ctx['overdue'] = Invoice.objects.filter(business__user=self.request.user).overdue()
        return ctx


class ListOverdueInvoiceView(NormalSecurityMixin, OwnerQuerySetMixin, ListView):
    model = Invoice
    template_name = 'invoices/overdue.html'
    queryset = Invoice.objects.overdue()
    user_field_name = 'business__user'


class CreateInvoiceView(NormalSecurityMixin, AutoUserMixin, InjectRequestFormMixin, CreateView):
    model = Invoice
    form_class = InvoiceCreateForm
    template_name = 'invoices/create.html'

    def get_initial(self):
        data = super(CreateInvoiceView, self).get_initial()
        # if url contains preselected options, then use them
        # eg. create invoice from business, customer list
        if self.request.GET.get('business'):
            data['business'] = self.request.GET.get('business')
        if self.request.GET.get('customer'):
            data['customer'] = self.request.GET.get('customer')
        return data


class LineItemInline(NormalSecurityMixin, InlineFormSet):
    model = LineItem
    form_class = LineItemForm
    extra = 10
    max_num = 20


class UpdateInvoiceView(NormalSecurityMixin, InjectRequestFormMixin, UpdateWithInlinesView):
    model = Invoice
    form_class = InvoiceUpdateForm
    slug_url_kwarg = 'uuid'
    slug_field = 'uuid'
    inlines = [LineItemInline]
    template_name = 'invoices/update.html'


class InvoicePDFEmbededView(NormalSecurityMixin, DetailView):
    template_name = 'invoices/pdf.html'
    slug_url_kwarg = 'uuid'
    slug_field = 'uuid'
    model = Invoice

    def get_context_data(self, **kwargs):
        ctx = super(InvoicePDFEmbededView, self).get_context_data(**kwargs)
        ctx['email_body'] = self.request.POST.get('email_body') or get_template('invoices/email/body.txt').render(Context({'object': self.object}))
        return ctx

    def post(self, request, *args, **kwargs):
        resp = super(InvoicePDFEmbededView, self).get(request, *args, **kwargs)
        try:
            if 'send' in self.request.POST:
                self.object.send_email(self.request.POST.get('email_body'))
                messages.add_message(request, messages.SUCCESS, 'Great! The email has been sent out.')
        except:
            log.exception('Unable to send email')
            messages.add_message(request, messages.ERROR, 'Sorry, we were not able to send the email, please try again later.')
        return resp


class InvoicePDFView(TokenSecurityMixin, NormalSecurityMixin, PDFTemplateView):
    slug_url_kwarg = 'uuid'
    slug_field = 'uuid'

    def get_context_data(self, **kwargs):
        # temp monkey patch to swap in getters
        ctx = super(InvoicePDFView, self).get_context_data(**kwargs)
        self.object = get_object_or_404(Invoice, uuid=self.kwargs.get('uuid'))
        ctx['object'] = self.object
        self.footer_template = self.new_footer_template
        self.header_template = self.new_header_template
        return ctx

    def get_filename(self):
        return self.request.GET.get('filename', None)

    def get_template_names(self):
        return ['{}/body.html'.format(self.object.business.invoice_theme.path)]

    @property
    def new_header_template(self):
        return '{}/header.html'.format(self.object.business.invoice_theme.path)

    @property
    def new_footer_template(self):
        return '{}/footer.html'.format(self.object.business.invoice_theme.path)

templates/invoices/base.html
{% extends 'base.html' %}

templates/invoices/create.html
{% extends 'invoices/base.html' %}


{% block page_header %}Create Invoice{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
          <form method="POST" class="form-horizontal">
              {% csrf_token %}
              {{ form }}
              <input class="btn btn-primary" type="submit" value="Create"/>
          </form>
      </div>
  </div>
{% endblock %}

templates/invoices/list.html
{% extends 'invoices/base.html' %}
{% load humanize %}

{% block page_header %}All Invoices <a href="{% url 'invoices:create' %}" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>{% endblock %}
{% block content %}
    {% if overdue.count %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Important:</strong> <a href="{% url 'invoices:overdue' %}">You have overdue invoices</a>
    </div>
    {% endif %}
    <div class="row">
      <div class="col-md-12">
        {% include 'invoices/partials/invoice_list_table.html' %}
      </div>
    <div class="row">
      <div class="col-md-12 pagination-centered text-center">
          {% include 'partials/pagination.html' with urlname='invoices:list' %}
      </div>
    </div>
{% endblock %}

templates/invoices/overdue.html
{% extends 'invoices/base.html' %}
{% load humanize %}

{% block page_header %}Overdue Invoices{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
        {% include 'invoices/partials/invoice_list_table.html' %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 pagination-centered text-center">
          {% include 'partials/pagination.html' with urlname='invoices:list' %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
            <a class="btn" href="{% url 'invoices:create' %}">Create</a>
      </div>
    </div>
{% endblock %}

templates/invoices/pdf.html
{% extends 'invoices/base.html' %}
{% load humanize %}

{% block page_header %}PDF View #{{ object.number }} <button data-toggle="modal" data-target="#email-form" class="btn btn-primary"><span class="glyphicon glyphicon-send" aria-hidden="true"></span> Email</button> <a href="{{ object.get_absolute_pdf_url }}?filename={{ object.number }}.pdf" class="btn btn-primary"><span class="glyphicon glyphicon-download" aria-hidden="true"></span> Download</a>{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <object data="{{ object.get_absolute_pdf_url }}" type="application/pdf" width="100%" height="800px">
      <a href="{{ object.get_absolute_pdf_url }}">Link to the PDF</a>
    </object>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="email-form">
  <form method="POST">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Send Invoice</h4>
        </div>
        <div class="modal-body">
            {% csrf_token %}
            <div class="form-group">
              <label for="email_body">Email Body</label>
              <textarea name="email_body" class="form-control">{{ email_body }}</textarea>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input type="submit" name="send" class="btn btn-primary" value="Send Email"/>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </form>
</div><!-- /.modal -->
{% endblock %}

templates/invoices/update.html
{% extends 'invoices/base.html' %}

{% block page_header %}Update Invoice: {{ object.number }}{% endblock %}
{% block content %}
<form method="POST" class="form-horizontal">
    <div class="row">
        <div class="col-md-12">
          {% csrf_token %}
          {{ form }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% for formset in inlines %}
                {{ formset.management_form }}
                <div class="row">
                    <div class="cols-md-12">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Particular</th>
                                    <th>Unit Price</th>
                                    <th>Quantity</th>
                                    <th>Tax %</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item_form in formset %}
                                <tr>
                                    {% for field in item_form %}
                                        {% if field.name == 'invoice' or field.name == 'id' %}
                                        {{ field }} {{ field.errors }}
                                        {% else %}
                                            <td>{{ field }}{{ field.errors }}</td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <input class="btn btn-primary" type="submit" value="Update"/>
    <a target="_blank" href="{% url 'invoices:embed_pdf' object.uuid %}" class="btn btn-info">PDF</a>
</form>
{% endblock %}