accounting/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
admin.autodiscover()


urlpatterns = [
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r"^account/", include("account.urls")),
    url(r'^businesses/', include('apps.businesses.urls', namespace="businesses")),
    url(r'^customers/', include('apps.customers.urls', namespace="customers")),
    url(r'^invoices/', include('apps.invoices.urls', namespace="invoices")),
    url(r'^quotes/', include('apps.quotes.urls', namespace="quotes")),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('businesses:list')), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/api/businesses/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from rest_framework import routers
from django.conf.urls import url, include
from .views import BusinessViewSet

router = routers.DefaultRouter()
router.register(r'businesses', BusinessViewSet)

urlpatterns = [
    url(r'^', include(router.urls))
]

apps/businesses/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from . import views
from apps.contribs.regex.url import UUID4_REGEX_PARAM

urlpatterns = [
    url(r'^{}$'.format(UUID4_REGEX_PARAM), views.UpdateBusinessView.as_view(), name="update"),
    url(r'^create$', views.CreateBusinessView.as_view(), name="create"),
    url(r'^(?P<page>\d+)$', views.ListBusinessView.as_view(), name="list"),
    url(r'^$', views.ListBusinessView.as_view(), name="list"),
]

apps/businesses/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from apps.contribs.models import BaseModel


class Business(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=255)
    gst_number = models.CharField(max_length=255, blank=True)
    logo = models.ImageField(upload_to='businesses/logos', blank=True)
    slogan = models.CharField(max_length=255, blank=True)
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255)
    post_code = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255, blank=True)
    fax = models.CharField(max_length=255, blank=True)
    email = models.EmailField()
    invoice_header_content = models.TextField(blank=True)
    invoice_footer_content = models.TextField(blank=True)
    quote_header_content = models.TextField(blank=True)
    quote_footer_content = models.TextField(blank=True)
    initial_invoice_number = models.IntegerField(default=10000)
    initial_quote_number = models.IntegerField(default=10000)
    default_tax = models.DecimalField(max_digits=5, decimal_places=4, default='0.15')
    default_quote_expiry_days = models.IntegerField(default=14)
    default_invoice_due_days = models.IntegerField(default=30)
    invoice_theme = models.ForeignKey('invoices.Theme', default=1)
    quote_theme = models.ForeignKey('quotes.Theme', default=1)

    def get_absolute_url(self):
        return reverse('businesses:update', args=[self.uuid])

    @property
    def last_invoice(self):
        return self.invoices.order_by('-id').first()

apps/businesses/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from .models import Business
from apps.contribs.forms.widgets import PercentageInput
from apps.contribs.forms.fields import PercentageField
import floppyforms.__future__ as forms


class BusinessForm(forms.ModelForm):
    default_tax = PercentageField(widget=PercentageInput(attrs={'step': 'any'}), label="Default Tax %")

    class Meta:
        model = Business
        exclude = ['uuid', 'user']

apps/api/businesses/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from rest_framework import viewsets
from apps.businesses.models import Business
from apps.api.contribs.views import FilterUserMixin, UUIDMixin, AutoOwnerMixin
from apps.api.contribs.permissions import IsOwnerPermission
from .serializers import BusinessSerializer


class BusinessViewSet(AutoOwnerMixin, UUIDMixin, FilterUserMixin, viewsets.ModelViewSet):
    queryset = Business.objects.all()
    serializer_class = BusinessSerializer
    permissions = [IsOwnerPermission]

apps/businesses/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
from django.views.generic import CreateView, UpdateView, ListView
from apps.contribs.views.mixins import NormalSecurityMixin, AutoUserMixin, OwnerQuerySetMixin
from .models import Business
from .forms import BusinessForm


class CreateBusinessView(NormalSecurityMixin, AutoUserMixin, CreateView):
    model = Business
    form_class = BusinessForm
    template_name = 'businesses/create.html'


class UpdateBusinessView(NormalSecurityMixin, UpdateView):
    model = Business
    form_class = BusinessForm
    template_name = 'businesses/update.html'
    slug_url_kwarg = 'uuid'
    slug_field = 'uuid'


class ListBusinessView(NormalSecurityMixin, OwnerQuerySetMixin, ListView):
    model = Business
    template_name = 'businesses/list.html'

templates/businesses/base.html
{% extends 'base.html' %}

templates/businesses/create.html
{% extends 'businesses/base.html' %}

{% block page_header %}Create A Business{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
          <form method="POST" enctype="multipart/form-data" class="form-horizontal">
              {% csrf_token %}
              {{ form }}
              <input class="btn btn-primary" type="submit" value="Create"/>
          </form>
      </div>
  </div>
{% endblock %}

templates/businesses/list.html
{% extends 'businesses/base.html' %}
{% load humanize %}


{% block page_header %}All Businesses <a href="{% url 'businesses:create' %}" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th><th>Last Invoice</th><th>Issued To</th><th>Issued At</th><th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          {% with last_invoice=object.last_invoice %}
          <tr>
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
            </td>
            <td>
              <a href="{{ last_invoice.get_absolute_url }}"><span class="label label-primary">{{ last_invoice.number }}</span></a>
            </td>
            <td>
              {{ last_invoice.customer }}
            </td>
            <td>
              {{ last_invoice.created|naturaltime }}
            </td>
            <td>
              <a class="btn btn-primary" href="{% url 'invoices:create' %}?business={{ object.id }}">+ Invoice</a>
              <a class="btn btn-primary" href="{% url 'quotes:create' %}?business={{ object.id }}">+ Quote</a>
            </td>
          </tr>
          {% endwith %}
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-md-12 pagination-centered text-center">
          {% include 'partials/pagination.html' with urlname='businesses:list' %}
      </div>
    </div>
{% endblock %}

templates/businesses/update.html
{% extends 'businesses/base.html' %}
{% load thumbnail %}

{% block page_header %}Update Business: {{ object.name }}{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
          {% if form.errors %}{{ form.errors }}{% endif %}
          <form method="POST" enctype="multipart/form-data" class="form-horizontal">
              {% csrf_token %}
              {{ form }}
              <input class="btn btn-primary" type="submit" value="Update"/>
          </form>
      </div>
  </div>
{% endblock %}